on: [push, pull_request]

name: Clippy check

permissions:
  contents: read

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
      - run: cargo fmt --all -- --check
      - run: rustup component add clippy
      - run: cargo clippy --all-features -- -D warnings
