name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run check
      run: ./test-scripts/check.sh ./target/release/elfshaker ./test-scripts/artifacts/verification.pack
    - name: Generate random pack
      run: |
        pack=$(contrib/create-test-pack ./target/release/elfshaker 5 64)
        ./test-scripts/check.sh ./target/release/elfshaker "$pack"
