name: Testing Nix

on:
  push:
    branches: [ main, test-ci ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@master
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - uses: docker/setup-qemu-action@v2
      - name: Build
        run: nix build --log-lines 1000 .#release
      - name: ls
        run: ls -la result/

  build-macos-x86_64:
    runs-on: macos-13 # 13 runner is x86.
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@master
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - name: Build
        run: nix build --log-lines 1000 .#release
      - name: ls
        run: ls -la result/

  build-macos-arm64:
    runs-on: macos-14 # 14 runner is aarch64.
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@master
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - name: Build
        run: nix build --log-lines 1000 .#release
      - name: ls
        run: ls -la result/
